Fix C89 compillation on Ubuntu 20.04
The ssdp.c code uses variable declaration inside for loop,
which is not permitted by c89 standard.

Fix by declaring the variable out of loop.

/home/user/nDPI/ndpi-netfilter/src/../../src/lib/protocols/ssdp.c: In function ‘ndpi_search_ssdp’:
/home/user/nDPI/ndpi-netfilter/src/../../src/lib/protocols/ssdp.c:231:7: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  231 |       for (unsigned int i=0; i < sizeof(SSDP_METHODS)/sizeof(SSDP_METHODS[0]); i++) {
      |       ^~~
/home/user/nDPI/ndpi-netfilter/src/../../src/lib/protocols/ssdp.c:231:7: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code